config/routes.rb
Sed::Application.routes.draw do

    resources :programas do 
        resources :grupos
    end

    resources :unidades do
        resources :temas
    end

    resources :temas do 
        resources :actividades
    end

    resources :evaluaciones do 
        member do 
            get :download 
        end
    end     

    get "home/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login"  => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    
    match "/update_grupos" => "estudiantes#update_grupos"

    resources :users

    resources :sessions

    resources :estudiantes

    resources :tpodocumentos

    resources :grupos

    resources :actividades

    resources :evaluaciones 

    resources :actividades

    resources :temas

    resources :unidades

    resources :programas

    root :to => "home#index"
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :tema
  attr_accessible :descripcion, :nombre, :tema_id

  	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :grupo
  belongs_to :tpodocumento
  belongs_to :programa
  attr_accessible :apellido, :cel, :direccion, :documento, :email, :fechana, :nombre, :tel, :tpodocumento_id, :grupo_id, :programa_id

	

	def self.search(search)
		where('nombre like ? or documento like ? or email like ? ',"%#{search}%" ,"%#{search}%","%#{search}%")
	end

end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  attr_accessible :calificacion, :datevalu, :archivo

	has_attached_file :archivo, :styles => {},
		:url  => "/assets/evaluaciones/:id/:style/:basename.:extension",
        :path => ":rails_root/public/assets/evaluaciones/:id/:style/:basename.:extension"

	validates_attachment_presence :archivo
	validates_attachment_size :archivo, :less_than => 5.megabytes
	validates_attachment_content_type :archivo, :content_type => ['text/plain', 'application/pdf']

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
  attr_accessible :ficha, :programa_id

  def self.search(search)
		where('ficha like ? ',"%#{search}%")
  end

end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :unidades
	has_many :grupos
	has_many :estudiantes
  attr_accessible :nombre


	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/tema.rb
class Tema < ActiveRecord::Base
	belongs_to :unidad
	has_many :actividades
  attr_accessible :nombre, :descripcion, :unidad_id

	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end
  
end

app/models/tpodocumento.rb
class Tpodocumento < ActiveRecord::Base

  attr_accessible :nombre

  validates :nombre, :presence=>true,
	:length => { :minimum =>3, :maximum => 80 }

end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
	belongs_to :programa
	has_many :temas
 	attr_accessible :nombre, :programa_id

  	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
	 attr_accessible :username, :password, :password_confirmation, :email
	 
	 validates_confirmation_of :password
	 validates_presence_of :password, :on => :create
	 validates_presence_of :email
	 validates_uniqueness_of :email
	 validates_presence_of :username
	 validates_uniqueness_of :username


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_filter :require_login
  def index
  end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_filter :require_login
  before_filter :find_unidad_temas

  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 0)
     @nrp = 3
   end 

    @temas = @unidad.temas.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page])      


    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @temas }
    end
  end

  def show
    @tema = Tema.find(params[:id])    
  end

  def new
    @tema = Tema.new
  end

  def edit
    @tema = Tema.find(params[:id])    
  end

  def create
    @tema = @unidad.temas.build(params[:tema])
    render :action => :new unless @tema.save
    @temas = Tema.all
  end

  def update
    @tema = Tema.find(params[:id])
    render :action => :edit unless @tema.update_attributes(params[:tema])

  end

  def destroy
    @tema = Tema.find(params[:id])
    @tema.destroy
    @temas = Tema.all
  end

  private

  def find_unidad_temas
    @unidad = Unidad.find(params[:unidad_id])
    @tema = Tema.find(params[:id]) if params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login
 def index
   @users = User.all

   respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
 end

 def new
   @user = User.new
 end

 def create
   @user = User.new(params[:user])
   if @user.save
     redirect_to root_url, :notice => "Cuenta Creada!"
   else
     render :new
   end
 end

 def edit
   @user = User.find(params[:id])
 end

 def update
   @user = User.find(params[:id])
   respond_to do |format|
     if @user.update_attributes(params[:user])
       format.html { redirect_to users_path, notice: 'Escalado talla was successfully updated.' }
       format.json { head :no_content }
     else
       format.html { render action: "edit" }
       format.json { render json: @user.errors, status: :unprocessable_entity }
     end
   end
 end

 def destroy
  @user = User.find(params[:id])
  @user.destroy
 end

end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/evaluaciones_helper.rb
module EvaluacionesHelper
	#if archivo == 'text/plain' 
		#image_tag	
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/helpers/tpodocumentos_helper.rb
module TpodocumentosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/temas/_form.html.erb
<%= simple_form_for([@unidad, @tema], :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

	<%= f.error_notification %>

  	<%= f.input :nombre, :label => "Nombre" %>
  	<%= f.label :descripcion %>
  	<%= f.text_area(:descripcion, :rows => 5) %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                unidad_temas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/temas/_show.html.erb
<%- model_class = Tema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='programa'>
 
  <p><b>Tema: </b><%= @tema.nombre %></p>
  <p><b>Programa: </b><%= @tema.unidad.programa.nombre %></p>
  <p><b>Unidad: </b><%= @tema.unidad.nombre %></p>
  <p><b>Descripcion: </b><%= @tema.descripcion %></p>

 
</div>

app/views/temas/_tema.html.erb
<tr id=<%= "tema_#{tema.id}" %>>

  <td><%= tema.nombre %></td>
  <td><%= tema.unidad.programa.nombre %></td>
  <td><%= tema.unidad.nombre %></td>
  <td><%= tema.descripcion %></td>
  <td>

    <div class="btn-group" >
      <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><i><%= image_tag("config.png")%></i></a>
     <ul class="dropdown-menu">
          <li><%= link_to unidad_tema_path(@unidad, tema), :remote => true, :class => 'btn btn-mini btn-info'  do %>
             <i><%=image_tag("ver.png")%></i>
              <% end %>
          </li>
          <li>
           <%= link_to edit_unidad_tema_path(@unidad, tema), :remote => true, :class => 'btn btn-mini'  do %>
           <i><%=image_tag("edit.png")%></i>
           <% end %>
          </li>
          <li>
             <%= link_to unidad_tema_path(@unidad, tema), :data => { :confirm => 'Esta Seguro?' }, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger'  do %>
             <i><%=image_tag("del.png")%></i>
             <% end %>
          </li>
      </ul>
    </div> 

    </td>
    <td><%= link_to "Actividades", tema_actividades_path(tema),  :class=>"btn btn-inverse" %>
    </td>
</tr>

app/views/temas/create.js.erb
$('table tbody').append("<%= escape_javascript(render @tema) %>")
$.lazybox.close()
$("input#totalregs").attr('value','<%= @temas.count %>');

app/views/temas/destroy.js.erb
$("table tr#tema_<%= @tema.id %>").remove();
$("input#totalregs").attr('value','<%= @temas.count %>');

app/views/temas/index.html.erb
<%- model_class = Tema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

  <%= form_tag request.path, :method => 'get' do %>
    Datos a Buscar:
    <div class="input-append">
      <%= search_field_tag :search, params[:search], :placeholder => "Nombre" %>
      <%= submit_tag "Consultar", :class => "btn btn-inverse ", :name => nil %>
    </div>
    <p>numero de registros
   <p><%= text_field_tag :registro, params[:registro], options={:class=>"span1"} %></p>
    <% end %>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pograma</th>
      <th>Materia</th>
      <th>Descripcion</th>
      <th><%=t '.acciones', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @temas %>
  </tbody>
</table>

<tfoot>
  <td>
   <%= link_to "Nuevo tema", new_unidad_tema_path, :remote =>true, :class =>'btn btn-info btn-small' %>
 </td>

 <td><%= link_to unidades_path,:class =>" btn btn-info" do %> <i><%= image_tag('back.png') %></i> <%end %></td>
</tfoot>

<div class="pagination pagination-centered">
    <ul>
    <%= will_paginate @temas, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  <br>
    <td>Total temas: <%= @temas.total_entries %> </td>
  </div>

app/views/temas/update.js.erb
$('tr#tema_<%= @tema.id %>').replaceWith("<%= escape_javascript(render @tema) %>")
$.lazybox.close()

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal offset3', :id => 'ej' } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field control-group">
    <%= f.label :username, :class => 'control-label ' %>
    <div class ="controls">
     <%= f.text_field :username %>
    </div> 
  </div>
  <div class="field control-group">
    <%= f.label :email %>
    <div class ="controls">
     <%= f.text_field :email %>
    </div> 
  </div>
  <div class="field control-group">
    <%= f.label :password %>
    <div class ="controls">
     <%= f.password_field :password %>
    </div> 
  </div>
  <div class="field control-group">
    <%= f.label :password_confirmacion %>
    <div class ="controls">
     <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="control-group">
   <div class ="controls">
    <%= f.submit 'crear usuario', :class => 'btn btn-info'%>
   </div>
    
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:crypted_password) %>:</strong></dt>
  <dd><%= @user.crypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salt) %>:</strong></dt>
  <dd><%= @user.salt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_me_token) %>:</strong></dt>
  <dd><%= @user.remember_me_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_me_token_expires_at) %>:</strong></dt>
  <dd><%= @user.remember_me_token_expires_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>