config/routes.rb
Sed::Application.routes.draw do

    resources :programas do 
        resources :grupos
    end

    resources :unidades do
        resources :temas
    end

    resources :temas do 
        resources :actividades
    end

    resources :evaluaciones do 
        member do 
            get :download 
        end
    end     

    get "home/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login"  => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    
    match "/update_grupos" => "estudiantes#update_grupos"

    resources :users

    resources :sessions

    resources :estudiantes

    resources :tpodocumentos

    resources :grupos

    resources :actividades

    resources :evaluaciones 

    resources :actividades

    resources :temas

    resources :unidades

    resources :programas

    root :to => "home#index"
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :tema
  attr_accessible :descripcion, :nombre, :tema_id

  	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :grupo
  belongs_to :tpodocumento
  belongs_to :programa
  attr_accessible :apellido, :cel, :direccion, :documento, :email, :fechana, :nombre, :tel, :tpodocumento_id, :grupo_id, :programa_id

	

	def self.search(search)
		where('nombre like ? or documento like ? or email like ? ',"%#{search}%" ,"%#{search}%","%#{search}%")
	end

end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  attr_accessible :calificacion, :datevalu, :archivo

	has_attached_file :archivo, :styles => {},
		:url  => "/assets/evaluaciones/:id/:style/:basename.:extension",
        :path => ":rails_root/public/assets/evaluaciones/:id/:style/:basename.:extension"

	validates_attachment_presence :archivo
	validates_attachment_size :archivo, :less_than => 5.megabytes
	validates_attachment_content_type :archivo, :content_type => ['text/plain', 'application/pdf']

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
  attr_accessible :ficha, :programa_id

  def self.search(search)
		where('ficha like ? ',"%#{search}%")
  end

end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :unidades
	has_many :grupos
	has_many :estudiantes
  attr_accessible :nombre


	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/tema.rb
class Tema < ActiveRecord::Base
	belongs_to :unidad
	has_many :actividades
  attr_accessible :nombre, :descripcion, :unidad_id

	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end
  
end

app/models/tpodocumento.rb
class Tpodocumento < ActiveRecord::Base

  attr_accessible :nombre

  validates :nombre, :presence=>true,
	:length => { :minimum =>3, :maximum => 80 }

end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
	belongs_to :programa
	has_many :temas
 	attr_accessible :nombre, :programa_id

  	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
	 attr_accessible :username, :password, :password_confirmation, :email
	 
	 validates_confirmation_of :password
	 validates_presence_of :password, :on => :create
	 validates_presence_of :email
	 validates_uniqueness_of :email
	 validates_presence_of :username
	 validates_uniqueness_of :username


end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
 before_filter :require_login
  before_filter :find_programa_grupos

  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 0)
     @nrp = 3
   end 

    @grupos = @programa.grupos.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page])      


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grupos }
    end
  end

  def new
    @grupo = Grupo.new
  end

  def create
    @grupo = @programa.grupos.build(params[:grupo])
    #@grupo.programa_id = @programa.id
    render :action => :new unless @grupo.save
    @grupos = Grupo.all  
  end

  def update
    @grupo = Grupo.find(params[:id])
    render :action => :edit unless @grupo.update_attributes(params[:grupo])
  end

  def destroy
    @grupo = Grupo.find(params[:id])
    @grupo.destroy
    @grupos = Grupo.all
  end

  private

  def find_programa_grupos
    @programa = Programa.find(params[:programa_id])
    @grupo = Grupo.find(params[:id]) if params[:id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_filter :require_login
  def index
  end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_filter :require_login
  before_filter :find_unidad_temas

  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 0)
     @nrp = 3
   end 

    @temas = @unidad.temas.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page])      


    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @temas }
    end
  end

  def show
    @tema = Tema.find(params[:id])    
  end

  def new
    @tema = Tema.new
  end

  def edit
    @tema = Tema.find(params[:id])    
  end

  def create
    @tema = @unidad.temas.build(params[:tema])
    render :action => :new unless @tema.save
    @temas = Tema.all
  end

  def update
    @tema = Tema.find(params[:id])
    render :action => :edit unless @tema.update_attributes(params[:tema])

  end

  def destroy
    @tema = Tema.find(params[:id])
    @tema.destroy
    @temas = Tema.all
  end

  private

  def find_unidad_temas
    @unidad = Unidad.find(params[:unidad_id])
    @tema = Tema.find(params[:id]) if params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login
 def index
   @users = User.all

   respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
 end

 def new
   @user = User.new
 end

 def create
   @user = User.new(params[:user])
   if @user.save
     redirect_to root_url, :notice => "Cuenta Creada!"
   else
     render :new
   end
 end

 def edit
   @user = User.find(params[:id])
 end

 def update
   @user = User.find(params[:id])
   respond_to do |format|
     if @user.update_attributes(params[:user])
       format.html { redirect_to users_path, notice: 'Escalado talla was successfully updated.' }
       format.json { head :no_content }
     else
       format.html { render action: "edit" }
       format.json { render json: @user.errors, status: :unprocessable_entity }
     end
   end
 end

 def destroy
  @user = User.find(params[:id])
  @user.destroy
 end

end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/evaluaciones_helper.rb
module EvaluacionesHelper
	#if archivo == 'text/plain' 
		#image_tag	
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/grupos/_form.html.erb
<%= stylesheet_link_tag "application" %>
<%= simple_form_for([@programa, @grupo], :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

    <%= f.error_notification %>

    <%= f.input :ficha, :label =>'Ficha:' %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancelar', :default => t("helpers.links.cancel")), programa_grupos_path, :class => 'btn' %>
      
    </div>
<% end %>

app/views/grupos/_grupo.html.erb
<tr id=<%= "grupo_#{grupo.id}" %>>

  <td><%= grupo.programa.nombre %></td>
  <td><%= grupo.ficha %></td>
  <td>
	    <div class="btn-group" >
			<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><i><%= image_tag("config.png")%></i></a>
		 <ul class="dropdown-menu">
		      <li><%= link_to programa_grupo_path(@programa, grupo), :remote => true, :class => 'btn btn-mini btn-info'  do %>
		       	 <i><%=image_tag("ver.png")%></i>
		       		<% end %>
		      </li>
		      <li>
			     <%= link_to edit_programa_grupo_path(@programa, grupo), :remote => true, :class => 'btn btn-mini'  do %>
			     <i><%=image_tag("edit.png")%></i>
			     <% end %>
		      </li>
		      <li>
		         <%= link_to programa_grupo_path(@programa, grupo), :data => { :confirm => 'Esta Seguro?' }, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger'  do %>
		         <i><%=image_tag("del.png")%></i>
		         <% end %>
		      </li>
		  </ul>
		</div> 
  </td>
</tr> 

app/views/grupos/_show.html.erb
<%- model_class = Grupo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<div class='grupo'>
  <p><b>Ficha: </b><%= @grupo.ficha %></p>
</div>

app/views/grupos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @grupo) %>")
$.lazybox.close()
$("input#totalregs").attr('value','<%= @grupos.count %>');

app/views/grupos/destroy.js.erb
$("table tr#grupo_<%= @grupo.id %>").remove();
$("input#totalregs").attr('value','<%= @grupos.count %>');

app/views/grupos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/grupos/index.html.erb
<%- model_class = Grupo -%>
<div class="page-header">
  <center><h1>Fichas del Programa <%= @programa.nombre %></h1></center>

  <%= form_tag request.path, :method => 'get' do %>
    Datos a Buscar:
    <div class="input-append">
      <%= search_field_tag :search, params[:search], :placeholder => "nombre, Documento, email" %>
      <%= submit_tag "Consultar", :class => "btn btn-inverse ", :name => nil %>
    </div>
    <p>numero de registros
   <p><%= text_field_tag :registro, params[:registro], options={:class=>"span1"} %></p>
    <% end %>
    <br>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Programa</th>
      <th>Ficha</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
     <%= render @grupos %>
  </tbody>
  <tfoot>
  </tfoot>
</table>
    <tr>
      <td><%= link_to 'Nueva Ficha', new_programa_grupo_path,:class =>" btn btn-info btn-small", :remote => true %></td>

      <td><%= link_to programas_path,:class =>" btn btn-info" do %> <i><%= image_tag('back.png') %></i> <%end %></td>
    </tr>


    <div class="pagination pagination-centered">
    <ul>
    <%= will_paginate @grupos, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  <br>
    <td>Total Grupos: <%= @grupos.total_entries %> </td>
  </div>

app/views/grupos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/grupos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {cerrar: true, klass: 'sticker', fixed: true})

app/views/grupos/update.js.erb
$('tr#grupo_<%= @grupo.id %>').replaceWith("<%= escape_javascript(render @grupo) %>")
$.lazybox.close()