config/routes.rb
Sed::Application.routes.draw do

    resources :programas do 
        resources :grupos
    end

    resources :unidades do
        resources :temas
    end

    resources :temas do 
        resources :actividades
    end

    resources :evaluaciones do 
        member do 
            get :download 
        end
    end     

    get "home/index"
    get "logout" => "sessions#destroy", :as => "logout"
    get "login"  => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"
    
    match "/update_grupos" => "estudiantes#update_grupos"

    resources :users

    resources :sessions

    resources :estudiantes

    resources :tpodocumentos

    resources :grupos

    resources :actividades

    resources :evaluaciones 

    resources :actividades

    resources :temas

    resources :unidades

    resources :programas

    root :to => "home#index"
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :tema
  attr_accessible :descripcion, :nombre, :tema_id

  	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :grupo
  belongs_to :tpodocumento
  belongs_to :programa
  attr_accessible :apellido, :cel, :direccion, :documento, :email, :fechana, :nombre, :tel, :tpodocumento_id, :grupo_id, :programa_id

	

	def self.search(search)
		where('nombre like ? or documento like ? or email like ? ',"%#{search}%" ,"%#{search}%","%#{search}%")
	end

end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  attr_accessible :calificacion, :datevalu, :archivo

	has_attached_file :archivo, :styles => {},
		:url  => "/assets/evaluaciones/:id/:style/:basename.:extension",
        :path => ":rails_root/public/assets/evaluaciones/:id/:style/:basename.:extension"

	validates_attachment_presence :archivo
	validates_attachment_size :archivo, :less_than => 5.megabytes
	validates_attachment_content_type :archivo, :content_type => ['text/plain', 'application/pdf']

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
  attr_accessible :ficha, :programa_id

  def self.search(search)
		where('ficha like ? ',"%#{search}%")
  end

end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :unidades
	has_many :grupos
	has_many :estudiantes
  attr_accessible :nombre


	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/tema.rb
class Tema < ActiveRecord::Base
	belongs_to :unidad
	has_many :actividades
  attr_accessible :nombre, :descripcion, :unidad_id

	def self.search(search)
		where('nombre like ? ',"%#{search}%")
	end
  
end

app/models/tpodocumento.rb
class Tpodocumento < ActiveRecord::Base

  attr_accessible :nombre

  validates :nombre, :presence=>true,
	:length => { :minimum =>3, :maximum => 80 }

end

app/models/unidad.rb
class Unidad < ActiveRecord::Base
	belongs_to :programa
	has_many :temas
 	attr_accessible :nombre, :programa_id

  	def self.search(search)
		where('nombre like ?',"%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
	 attr_accessible :username, :password, :password_confirmation, :email
	 
	 validates_confirmation_of :password
	 validates_presence_of :password, :on => :create
	 validates_presence_of :email
	 validates_uniqueness_of :email
	 validates_presence_of :username
	 validates_uniqueness_of :username


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_filter :require_login
  def index
  end
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_filter :require_login
  before_filter :find_unidad_temas

  def index
    @nrp = (params[:registro] != nil)? params[:registro].to_i : 3

   if ((@nrp) <= 0)
     @nrp = 3
   end 

    @temas = @unidad.temas.search(params[:search]).paginate(:per_page=>(@nrp), :page=>params[:page])      


    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @temas }
    end
  end

  def show
    @tema = Tema.find(params[:id])    
  end

  def new
    @tema = Tema.new
  end

  def edit
    @tema = Tema.find(params[:id])    
  end

  def create
    @tema = @unidad.temas.build(params[:tema])
    render :action => :new unless @tema.save
    @temas = Tema.all
  end

  def update
    @tema = Tema.find(params[:id])
    render :action => :edit unless @tema.update_attributes(params[:tema])

  end

  def destroy
    @tema = Tema.find(params[:id])
    @tema.destroy
    @temas = Tema.all
  end

  private

  def find_unidad_temas
    @unidad = Unidad.find(params[:unidad_id])
    @tema = Tema.find(params[:id]) if params[:id]
  end

end

app/controllers/tpodocumentos_controller.rb
class TpodocumentosController < ApplicationController
  before_filter :require_login
  def index
    @tpodocumentos = Tpodocumento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tpodocumentos }
    end
  end

  def show
    @tpodocumento = Tpodocumento.find(params[:id])
  end

  def new
    @tpodocumento = Tpodocumento.new
  end

  def edit
    @tpodocumento = Tpodocumento.find(params[:id])
  end

  def create
    @tpodocumento = Tpodocumento.new(params[:tpodocumento])
    render :action => :new unless @tpodocumento.save
    @tpodocumento = Tpodocumento.all
  end

  def update
    @tpodocumento = Tpodocumento.find(params[:id])
    render :action => :edit unless @tpodocumento.update_attributes(params[:tpodocumento])
  end

  def destroy
    @tpodocumento = Tpodocumento.find(params[:id])
    @tpodocumento.destroy
  end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/evaluaciones_helper.rb
module EvaluacionesHelper
	#if archivo == 'text/plain' 
		#image_tag	
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/helpers/tpodocumentos_helper.rb
module TpodocumentosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tpodocumentos/_form.html.erb
<%= simple_form_for(@tpodocumento, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

	<%= f.error_notification %>

  <%= f.input :nombre, :label => 'Nombre:' %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tpodocumentos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tpodocumentos/_show.html.erb
<%- model_class = Tpodocumento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='tpodocumento'>
  <p><b>Nombre: </b><%= @tpodocumento.nombre %></p>
</div>

app/views/tpodocumentos/_tpodocumento.html.erb
<tr id=<%= "tpodocumento_#{tpodocumento.id}" %>>

  <td><%= tpodocumento.nombre %></td>
  <td>
    <%= link_to 'Informacion', tpodocumento, :remote => true, :class => 'btn btn-mini btn-info' %>
    <%= link_to 'Editar', edit_tpodocumento_path(tpodocumento), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', tpodocumento, :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/tpodocumentos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @tpodocumento) %>")
$.lazybox.close()

app/views/tpodocumentos/destroy.js.erb
$("table tr#tpodocumento_<%= @tpodocumento.id %>").remove();

app/views/tpodocumentos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/tpodocumentos/index.html.erb
<%- model_class = Tpodocumento -%>
  <div class="page-header">
    <h1>Tipo De Documentos</h1>
  </div>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Nombre</th>
      </tr>
    </thead>
    <tbody>
       <%= render @tpodocumentos %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
      <tr>
        <td><%= link_to 'Nuevo Tipo Documento', new_tpodocumento_path,:class =>" btn btn-info", :remote => true %></td>
      </tr>

app/views/tpodocumentos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/tpodocumentos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {cerrar: true, klass: 'sticker', fixed: true})

app/views/tpodocumentos/update.js.erb
$('tr#tpodocumento_<%= @tpodocumento.id %>').replaceWith("<%= escape_javascript(render @tpodocumento) %>")
$.lazybox.close()